<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_register</name>
   <tag></tag>
   <elementGuidId>dedb480c-4057-4160-8c55-5b8723656310</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mt-0.mr-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='formLogin']/div[5]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d1de958-3888-48b5-b2fa-245d96ee645b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://vcc.pln.co.id/register</value>
      <webElementGuid>519e344b-c63a-46c3-a708-5c7fabcc1117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-0 mr-5</value>
      <webElementGuid>024bfdef-e640-4e0b-9e3c-9f21cf7f6d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>register</value>
      <webElementGuid>713acfef-843f-4943-ad15-79ba7204fb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formLogin&quot;)/div[@class=&quot;ntlgn text-center mt-10&quot;]/p[@class=&quot;text-center mb-0&quot;]/a[@class=&quot;mt-0 mr-5&quot;]</value>
      <webElementGuid>bf1cd631-e19d-4a2d-8da8-ccfd854f0472</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formLogin']/div[5]/p/a</value>
      <webElementGuid>ffd4560e-07cc-4766-aac3-75c88888b25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'register')]</value>
      <webElementGuid>4c7fd23b-0904-4e43-8d87-fb92fee8af5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='login'])[1]/following::a[1]</value>
      <webElementGuid>0026c1cf-b858-4e01-a82c-6ffffba2715b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Captcha'])[1]/following::a[1]</value>
      <webElementGuid>9782b1ad-ecc5-475d-9d17-8a605402af1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='login'])[2]/preceding::a[1]</value>
      <webElementGuid>2c62e3a9-33b9-4cea-b0fd-9de29ab6e559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='register']/parent::*</value>
      <webElementGuid>63c2f92d-e3e3-4743-aa88-054c062ea044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://vcc.pln.co.id/register')]</value>
      <webElementGuid>308e035a-9529-4d87-85b8-72302221f8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>63f48019-ea0f-4549-81ba-d549b8d29e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://vcc.pln.co.id/register' and (text() = 'register' or . = 'register')]</value>
      <webElementGuid>d59fef67-5d06-474f-a227-c02532144287</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
