<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status Homescreen-message</name>
   <tag></tag>
   <elementGuidId>63a61a88-4ca1-4672-8683-cadde65fd048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='status_HOMESCREEN-MESSAGE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#status_HOMESCREEN-MESSAGE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec476938-2455-4b44-9cc9-fd1547c9dffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3</value>
      <webElementGuid>a3fa0d59-45df-4ac0-8767-efa8b2b7ba8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status_HOMESCREEN-MESSAGE</value>
      <webElementGuid>9875aab3-6fc3-49b9-b0c9-49e7d8726e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>0ff14a8f-cfa5-4887-9e72-a8ae3ed2a20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>67c69d5b-1043-41d5-8f7c-f19b50499d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status_HOMESCREEN-MESSAGE&quot;)</value>
      <webElementGuid>6d96e3bb-4dba-4562-a06f-5759079fa3e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='status_HOMESCREEN-MESSAGE']</value>
      <webElementGuid>9c128445-345b-4dba-b9c2-93231d46097c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[6]/label[2]/span/span/input</value>
      <webElementGuid>b7e1f84f-0bea-4679-b8e1-1a604b884221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/label[2]/span/span/input</value>
      <webElementGuid>9f192b3f-19d9-4920-bb06-19c36eb20c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'status_HOMESCREEN-MESSAGE' and @name = 'status' and @type = 'checkbox']</value>
      <webElementGuid>9b212a3f-54b4-450a-b79e-cc0984f43fec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
