<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status Maintenance-Mode</name>
   <tag></tag>
   <elementGuidId>a8db68b7-92c4-44cd-9fef-94d7c940426c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='status_MAINTENANCE-MODE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#status_MAINTENANCE-MODE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bbe8dad-7f24-4e32-8e67-ccd5a9a82ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3</value>
      <webElementGuid>07320345-ce19-4a3c-a397-1d646f44d6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status_MAINTENANCE-MODE</value>
      <webElementGuid>eaa36a6d-fa80-4332-9067-93e684c036be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>81d65bd5-969a-4c66-a4bc-7aaf0a6b71cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4183cd44-5227-4480-b16e-27b5bf0aa84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status_MAINTENANCE-MODE&quot;)</value>
      <webElementGuid>0ad8c4fa-119e-41be-905b-b15ac3dc35d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='status_MAINTENANCE-MODE']</value>
      <webElementGuid>e42b485a-8444-4a37-b5c2-4acdb72cb628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[9]/label[2]/span/span/input</value>
      <webElementGuid>44594f46-99c8-442e-978d-bb6eaa660eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/label[2]/span/span/input</value>
      <webElementGuid>e5b954b0-4cc6-4cd2-b940-958d2686cee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'status_MAINTENANCE-MODE' and @name = 'status' and @type = 'checkbox']</value>
      <webElementGuid>689eba43-9696-43d2-8dc3-5c0b9791c806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
