<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_UBAH</name>
   <tag></tag>
   <elementGuidId>590ece13-cbb2-4ae8-b06f-71905ca04cc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[5]/table/tbody/tr/td[9]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b1188623-2ac0-474e-9f93-0e3b1a6bd8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vcc-btn contained-warning text-[12px] !px-[12px] !py-[6px]</value>
      <webElementGuid>c9afbbe6-8541-469c-aec8-63bb1e64f8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/user-management/user/update/aed234aa-0f57-4190-89c8-06783951958e</value>
      <webElementGuid>543ef9e5-f9ba-4b59-8175-5a58b845b32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UBAH</value>
      <webElementGuid>f5d1d422-65c2-4988-8d3b-fae1781ed679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;px-[64px] py-8 mx-auto mt-28 mb-28 max-w-screen-2xl relative&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiTableContainer-root table-app-primary scrollable-x max-h-[625px] overflow-auto css-13xy2my&quot;]/table[@class=&quot;MuiTable-root css-1owb465&quot;]/tbody[@class=&quot;MuiTableBody-root css-1xnox0e&quot;]/tr[@class=&quot;MuiTableRow-root css-1gqug66&quot;]/td[@class=&quot;MuiTableCell-root MuiTableCell-body MuiTableCell-alignLeft MuiTableCell-sizeMedium  css-8juoir&quot;]/div[@class=&quot;flex gap-2&quot;]/a[@class=&quot;vcc-btn contained-warning text-[12px] !px-[12px] !py-[6px]&quot;]</value>
      <webElementGuid>d55f5651-9238-4e82-a230-3aaed5dd3dbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[5]/table/tbody/tr/td[9]/div/a</value>
      <webElementGuid>13345990-4b93-46dc-b6af-d701bed76d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'UBAH')]</value>
      <webElementGuid>0f82dc10-0a76-48ec-9e41-7f2a2a6b7328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIHAT'])[1]/following::a[1]</value>
      <webElementGuid>f7bbad31-2836-4d80-a790-c99e275d7eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[7]/following::a[1]</value>
      <webElementGuid>5809ea37-b695-4df3-9bce-5b1f1bfc5a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAPUS'])[1]/preceding::a[1]</value>
      <webElementGuid>434c81bf-429a-42ca-872a-ad80ba5764b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test user'])[1]/preceding::a[1]</value>
      <webElementGuid>77adae51-ea2e-45f9-90ef-67caf7cc3918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='UBAH']/parent::*</value>
      <webElementGuid>b43e8f97-7aa7-483c-ae24-de81adeda49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/user-management/user/update/aed234aa-0f57-4190-89c8-06783951958e')]</value>
      <webElementGuid>d4bfde39-8795-4c26-97a1-5531cbe1a82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/a</value>
      <webElementGuid>ce8e0a93-8a18-4326-a7e3-c8ba1317fc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/user-management/user/update/aed234aa-0f57-4190-89c8-06783951958e' and (text() = 'UBAH' or . = 'UBAH')]</value>
      <webElementGuid>43a565f0-901e-4729-994d-b5306020c47b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
