<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jabatan_jabatan</name>
   <tag></tag>
   <elementGuidId>024d07a1-3746-4a50-b16c-99539a571f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jabatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jabatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>928eee49-eb9a-41ee-911e-918a8e6a73ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>56eb6507-371b-467f-9858-c16c37a0c861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jabatan</value>
      <webElementGuid>1be52973-ac38-4369-999f-935c3ef1e494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jabatan</value>
      <webElementGuid>be171400-91c7-40be-b120-1ebd8016acdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jabatan</value>
      <webElementGuid>d7ccc7fb-7a95-4715-9603-6567ac4e8599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d903a399-4426-4dc2-89bc-bf01643219ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>9e5a6252-7105-430d-ac77-0bff3d47763d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>jabatan-helper-text</value>
      <webElementGuid>2842a73a-c2ad-49a8-b211-68fce8dc7258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jabatan&quot;)</value>
      <webElementGuid>38b6c5eb-2108-4bb7-bc3e-f662a56f3eda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jabatan']</value>
      <webElementGuid>fe875ad0-67bc-4de7-8657-36e3ff588848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/form/div[2]/div[5]/div/div/input</value>
      <webElementGuid>bb5054d6-fd36-44d5-8d92-2c48ff39f624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>b08ed0f9-4c06-4105-88e5-f39dbc5b4bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jabatan' and @name = 'jabatan' and @placeholder = 'Jabatan' and @type = 'text']</value>
      <webElementGuid>9f8aaccd-93d6-4275-8379-e552b9b08cb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
