<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kembali_ss</name>
   <tag></tag>
   <elementGuidId>2ba136ef-6f8d-4912-b209-77d45812833e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rotate-180.mr-2.w-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af361a78-4725-4280-b45c-2fd0c2a17779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>arrow</value>
      <webElementGuid>d14d9685-eb8e-4176-86d8-cfd2654c7050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/icons-arrow-2.svg</value>
      <webElementGuid>e9171e74-21d2-49e1-afa4-a0663bcdfece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rotate-180 mr-2 w-6</value>
      <webElementGuid>2a599adf-89f3-4b91-9048-ee24470a9909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;px-[64px] py-8 mx-auto mt-24 mb-28 max-w-screen-2xl relative&quot;]/div[@class=&quot;flex items-center justify-between mt-49 mb-4 MuiBox-root css-0&quot;]/div[@class=&quot;flex items-center&quot;]/button[@class=&quot;!p-0 mr-2&quot;]/img[@class=&quot;rotate-180 mr-2 w-6&quot;]</value>
      <webElementGuid>2f4acf98-da2f-44a5-96b3-5c8bf9590653</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/button/img</value>
      <webElementGuid>9cd4950c-e1fd-43c7-a1a0-69cb26b6f5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='arrow']</value>
      <webElementGuid>1d4c1eab-7727-411b-8e70-8b708e953f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>a9dd9234-8d7d-4ed6-8f5e-55dda6f33d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'arrow' and @src = '/icons/icons-arrow-2.svg']</value>
      <webElementGuid>e39c98ec-2a0d-4d5a-b68a-c06391884088</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
