<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_UBAH</name>
   <tag></tag>
   <elementGuidId>89f34df6-ef2c-44cf-a50b-ab52f2c7db50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[5]/table/tbody/tr/td[9]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c98f1a2-9acc-4f33-a52e-7c20b0590c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vcc-btn contained-warning text-[12px] !px-[12px] !py-[6px]</value>
      <webElementGuid>ec46a80b-69af-4ea3-bf1c-9ef3809e44aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/user-management/user/update/5389d7da-09e3-4f4e-9160-c80f4bceb494</value>
      <webElementGuid>c6f97b14-a44e-4ab2-9eef-eff72ef72f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UBAH</value>
      <webElementGuid>8fa9d7c3-d82e-4e42-bfea-649fddc1828e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;px-[64px] py-8 mx-auto mt-28 mb-28 max-w-screen-2xl relative&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiTableContainer-root table-app-primary scrollabel-x css-13xy2my&quot;]/table[@class=&quot;MuiTable-root css-1owb465&quot;]/tbody[@class=&quot;MuiTableBody-root css-1xnox0e&quot;]/tr[@class=&quot;MuiTableRow-root css-1gqug66&quot;]/td[@class=&quot;MuiTableCell-root MuiTableCell-body MuiTableCell-alignLeft MuiTableCell-sizeMedium  css-8juoir&quot;]/div[@class=&quot;flex gap-2&quot;]/a[@class=&quot;vcc-btn contained-warning text-[12px] !px-[12px] !py-[6px]&quot;]</value>
      <webElementGuid>d41cfe47-d709-445e-9780-47a0872dd5e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[5]/table/tbody/tr/td[9]/div/a</value>
      <webElementGuid>79bec2c2-d30d-4081-bd47-663d999a870a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'UBAH')]</value>
      <webElementGuid>f2e5bc48-69d3-488c-9efd-b4525ba16eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIHAT'])[1]/following::a[1]</value>
      <webElementGuid>88636042-77a9-4dbd-abdf-33302cde5238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[7]/following::a[1]</value>
      <webElementGuid>6f20519e-9550-4ad2-9586-9ba6b3bba5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAPUS'])[1]/preceding::a[1]</value>
      <webElementGuid>77895350-f0c8-4657-88c5-d3adb25f62af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='adeirawan060614@gmail.com'])[1]/preceding::a[1]</value>
      <webElementGuid>5d34296d-8ead-41ad-bf2e-12c4c5cbf051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='UBAH']/parent::*</value>
      <webElementGuid>22c18e8a-80d0-4560-8e8e-b241841846ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/user-management/user/update/5389d7da-09e3-4f4e-9160-c80f4bceb494')]</value>
      <webElementGuid>ccbc1ed3-b568-4f8e-89ab-426524002e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/a</value>
      <webElementGuid>ca105e7e-9e3c-47b7-875c-d0762edffeeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/user-management/user/update/5389d7da-09e3-4f4e-9160-c80f4bceb494' and (text() = 'UBAH' or . = 'UBAH')]</value>
      <webElementGuid>366aaeee-d995-4fd0-b1ee-f254de8409bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[5]/table/tbody/tr[6]/td[9]/div/a</value>
      <webElementGuid>695f3d54-8193-48d1-b062-940b08f15930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'UBAH')])[6]</value>
      <webElementGuid>785ed869-bce9-4664-93b6-921f52d622cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIHAT'])[6]/following::a[1]</value>
      <webElementGuid>3d26c865-7a6e-4c33-b7cc-db6fdc0efc95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[12]/following::a[1]</value>
      <webElementGuid>b30fd112-3c52-4061-aff9-83f66559f6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAPUS'])[6]/preceding::a[1]</value>
      <webElementGuid>fe0c6049-eeaf-47d2-832a-d369d29beeb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tyas+reeng@oninyon.com'])[1]/preceding::a[1]</value>
      <webElementGuid>08421b3d-4ee9-442a-aa12-6384bbb9aff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/user-management/user/update/873428a0-3796-4f42-96a3-b70956726f1e')]</value>
      <webElementGuid>27f66d42-e14e-4b0a-8bfb-2d68eca06acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[9]/div/a</value>
      <webElementGuid>02051b71-94a1-4b37-b581-f8b28de408e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/user-management/user/update/873428a0-3796-4f42-96a3-b70956726f1e' and (text() = 'UBAH' or . = 'UBAH')]</value>
      <webElementGuid>e729c98f-051e-460f-9a5b-77507c599b59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
