<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ATUR PERMISSION_e2485d63-5d79-449a-a175-f41e3eb31224</name>
   <tag></tag>
   <elementGuidId>488e5cac-b448-4f2c-b634-eff05cde4c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;e2485d63-5d79-449a-a175-f41e3eb31224&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='e2485d63-5d79-449a-a175-f41e3eb31224']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb234077-9b84-47e8-8852-b62c5c95dc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input css-1m9pwf3</value>
      <webElementGuid>16f5f5cc-409b-4c73-bb4f-f1931a5e7074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e2485d63-5d79-449a-a175-f41e3eb31224</value>
      <webElementGuid>b294b400-750c-405f-b804-9d20d75ae780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>65a2f54e-c1f1-4e86-812b-580e91b51eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d98e7afb-d8bb-4a1b-bd77-55c984ca74d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;px-[64px] py-8 mx-auto mt-28 mb-28 max-w-screen-2xl relative&quot;]/form[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiFormControl-root MuiFormControl-fullWidth mb-8 css-tzsjye&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;py-1 px-3 border border-x border-[#E0E0E0] bg-[#FAFAFA] MuiBox-root css-0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiAccordion-root MuiAccordion-rounded MuiAccordion-gutters css-4of1v1&quot;]/div[@class=&quot;MuiButtonBase-root MuiAccordionSummary-root MuiAccordionSummary-gutters bg-[#FAFAFA] css-xfnbgk&quot;]/div[@class=&quot;MuiAccordionSummary-content MuiAccordionSummary-contentGutters css-l0jafl&quot;]/label[@class=&quot;MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd css-1nq71mm&quot;]/span[@class=&quot;MuiButtonBase-root MuiCheckbox-root MuiCheckbox-colorPrimary MuiCheckbox-sizeMedium PrivateSwitchBase-root MuiCheckbox-root MuiCheckbox-colorPrimary MuiCheckbox-sizeMedium MuiCheckbox-root MuiCheckbox-colorPrimary MuiCheckbox-sizeMedium css-zun73v&quot;]/input[@class=&quot;PrivateSwitchBase-input css-1m9pwf3&quot;]</value>
      <webElementGuid>d55951b1-2629-4e11-9de6-417bf9db099e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='e2485d63-5d79-449a-a175-f41e3eb31224']</value>
      <webElementGuid>f8219532-0286-417b-9754-2de1dab2f8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/form/div[5]/div/div/div/div/div/label/span/input</value>
      <webElementGuid>e3d423be-ecc2-4595-a1df-0252d1f8365b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label/span/input</value>
      <webElementGuid>5c68744f-5cf0-4026-a543-c52b36a51a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'e2485d63-5d79-449a-a175-f41e3eb31224' and @type = 'checkbox']</value>
      <webElementGuid>fd7a2ebc-ddca-4854-8db0-32d5404d7f72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
