<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SULMAPANA</name>
   <tag></tag>
   <elementGuidId>ecb7e3bd-ddb3-44ba-9baf-d43bc44ee256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='FI_federated.0mtpjz80f7h9ht17gtcgo088nerk,none:REGIONAL:nk3150806985899305519_93806661854111611_2']/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;SULMAPANA&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1938a82d-8008-43fc-a526-4b724d78d698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SULMAPANA</value>
      <webElementGuid>355dd9f1-674c-4ace-b119-046bb3bf2838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SULMAPANA</value>
      <webElementGuid>e58fea8b-13c4-4e30-a94b-823588567b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FI_federated.0mtpjz80f7h9ht17gtcgo088nerk,none:REGIONAL:nk3150806985899305519_93806661854111611_2&quot;)/div[@class=&quot;facetOverflow&quot;]/a[1]</value>
      <webElementGuid>1356add2-38af-48ca-bf3d-b82c64196ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Outage/Dashboard/Analisis Kinerja Yantek/iframe_Analisis Kinerja Yantek_tableauViz h_76ae7b</value>
      <webElementGuid>8d9888af-0349-463f-b55c-a3f7b2f20808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FI_federated.0mtpjz80f7h9ht17gtcgo088nerk,none:REGIONAL:nk3150806985899305519_93806661854111611_2']/div[2]/a</value>
      <webElementGuid>8c87077e-800b-4da0-9551-63e791b96085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SULMAPANA')]</value>
      <webElementGuid>1d9c305b-4a50-4e25-b999-38f4c7adaf7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAMALI'])[2]/following::a[1]</value>
      <webElementGuid>dcaf7c6a-cab1-42a8-8f99-fff6fe4672ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Null'])[1]/following::a[2]</value>
      <webElementGuid>d3886a2a-fee6-4870-933f-ca686b4f8217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMKAL'])[1]/preceding::a[1]</value>
      <webElementGuid>42fd3839-3751-4c3c-9019-654ca7defe30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SULMAPANA']/parent::*</value>
      <webElementGuid>3aa64d6a-4ba2-441d-a85c-f99b5909a081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>c81fa443-5b0c-41d6-961d-4e2ee622bf90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'SULMAPANA' and (text() = 'SULMAPANA' or . = 'SULMAPANA')]</value>
      <webElementGuid>b29141a1-df44-4caa-bda8-3800f78e2dbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
