<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Analisis Kinerja Yantek_tableauViz h_76ae7b</name>
   <tag></tag>
   <elementGuidId>ac10495c-3dd5-4cc8-b6db-96b725343349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[3]/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.tableauViz.h-screen.w-full.z-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>56fb6dd6-0178-42ca-bcae-717146590ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa3c62f6-bae6-4412-9861-b9a5b1379b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9a4126f8-0c6d-4982-9aed-1ffa2c8a2085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>84968ce3-67de-4722-9891-5e319e426825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Data Visualisation</value>
      <webElementGuid>39460cfa-4923-4eaf-ad7b-7fdbeba87cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9cf4a2e1-777a-4a59-99f1-9e0ac8d7b862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b4e5f895-7dba-45e9-b352-38141919de1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableauViz h-screen w-full z-1</value>
      <webElementGuid>d0f63479-ac21-4ec0-b9a8-b7df4925e863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bigdata.pln.co.id/trusted/tQKhlxXwSAyMVt1BX6lK8g==:FAM2hS3PO5nh37dWUdww3K6F/views/YantekOptimization_16395326114070/DashboardRecapPerformance?:embed=y&amp;:showVizHome=no&amp;:host_url=https://bigdata.pln.co.id/&amp;:embed_code_version=3&amp;:tabs=yes&amp;:toolbar=yes&amp;:showAppBanner=false&amp;:display_spinner=no&amp;:loadOrderID=0</value>
      <webElementGuid>747960a2-a219-4d25-af31-04d45a517a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;px-[64px] py-8 mx-auto mt-24 mb-28 max-w-screen-2xl relative&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;tableauPlaceholder&quot;]/iframe[@class=&quot;tableauViz h-screen w-full z-1&quot;]</value>
      <webElementGuid>032b68b1-5ce4-496e-a0a9-c61f38c0238b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[3]/div/iframe</value>
      <webElementGuid>803bac3e-c262-4bf4-afe7-b28517f61335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c9b5aef5-2a59-4016-af41-da656c5c4ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Data Visualisation' and @src = 'https://bigdata.pln.co.id/trusted/tQKhlxXwSAyMVt1BX6lK8g==:FAM2hS3PO5nh37dWUdww3K6F/views/YantekOptimization_16395326114070/DashboardRecapPerformance?:embed=y&amp;:showVizHome=no&amp;:host_url=https://bigdata.pln.co.id/&amp;:embed_code_version=3&amp;:tabs=yes&amp;:toolbar=yes&amp;:showAppBanner=false&amp;:display_spinner=no&amp;:loadOrderID=0']</value>
      <webElementGuid>63a314c3-47b4-43e9-bf6f-607e81f04b7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
