<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_register</name>
   <tag></tag>
   <elementGuidId>717410d6-a0c1-4410-8a81-faa6499afcf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.vcc-btn.vcc-btn-md.contained-primary.uppercase</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c3142fb-ee71-4c72-b465-00b84272433b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vcc-btn vcc-btn-md contained-primary uppercase</value>
      <webElementGuid>ab15645c-9d7e-427b-b371-bd8835cc56eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e7353257-d873-4d79-9779-2de4740a8b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>register</value>
      <webElementGuid>3236ec9d-0710-43bf-9c47-76fc00a1b9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;auth-page h-screen&quot;]/div[@class=&quot;auth-card w-[500px] !pt-[32px]&quot;]/div[@class=&quot;animate__animated animate__fadeIn&quot;]/div[@class=&quot;flex gap-4&quot;]/button[@class=&quot;vcc-btn vcc-btn-md contained-primary uppercase&quot;]</value>
      <webElementGuid>2eb2db94-a388-4407-b61c-3376a8c01e94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>62b29a83-931a-4aa3-8dc3-1bd637294c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/button[2]</value>
      <webElementGuid>198f60fe-ea21-44e2-9072-5c82c3089eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cancel'])[1]/following::button[1]</value>
      <webElementGuid>cd4c6535-1403-441f-8b89-50e90703e25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Mohon dipastikan Level Unit dan Kode Unit yang Anda pilih sesuai dengan lokasi Anda sebenarnya'])[1]/following::button[2]</value>
      <webElementGuid>a51faf39-5d4d-45cf-9031-457fe919b78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohon tunggu, sedang memuat data...'])[1]/preceding::button[1]</value>
      <webElementGuid>694c606f-8744-4c3d-92f8-9e9d965982d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error!'])[1]/preceding::button[1]</value>
      <webElementGuid>6ce5da81-5e0c-4d02-b151-a784ac0ef82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='register']/parent::*</value>
      <webElementGuid>7db2934c-6f92-4fa5-a53e-9953985a2d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>0d0625e2-7b34-4573-a161-bd6790494aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'register' or . = 'register')]</value>
      <webElementGuid>05904bcf-dd4b-45c1-867b-7d6843b32b55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
