<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>K_WO belum</name>
   <tag></tag>
   <elementGuidId>a261c6f3-99e0-4bf6-9d17-b0984d587da6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[6]/div[3]/div/div[2]/div/div[2]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64031580-6f38-4245-9d0a-d17bc7f7af5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-[#E2AD0C] text-[14px] text-[#FFF] px-[8px] py-[4px] rounded-[50px]</value>
      <webElementGuid>ceb10e55-9ced-4e74-a54c-e3a6caeaf631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Wo Belum Ditindaklanjut</value>
      <webElementGuid>94e5171f-b39c-4686-b996-6725a9912afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/outage/monitoring/detail?type=kl&amp;data=y&amp;tab=1</value>
      <webElementGuid>7a5f4933-2795-4bf4-a693-3f939a4d324d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>013d771e-b523-42f4-9e9e-cf9e8caeef77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;px-[64px] py-8 mx-auto mt-24 mb-28 max-w-screen-2xl relative&quot;]/div[@class=&quot;md:w-full lg:w-6/12 bg-[#E7F6F9] mx-auto mb-10 p-4 rounded&quot;]/div[@class=&quot;grid gap-2&quot;]/div[1]/div[@class=&quot;bg-[#FFF] rounded px-4 py-2 gap-x-2 mb-[1px]&quot;]/div[@class=&quot;flex items-center&quot;]/div[@class=&quot;flex items-center w-full gap-x-10&quot;]/a[@class=&quot;bg-[#E2AD0C] text-[14px] text-[#FFF] px-[8px] py-[4px] rounded-[50px]&quot;]</value>
      <webElementGuid>559ba11c-9933-45c2-a53c-6ff0bd10a50b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[6]/div[3]/div/div[2]/div/div[2]/a[3]</value>
      <webElementGuid>f4935af2-a0e9-4dfa-819a-cbe5ba294fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'255')]</value>
      <webElementGuid>0be30b43-6dd2-470b-978e-cc868b47ab38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[2]/following::a[3]</value>
      <webElementGuid>2c8ca9cb-67b7-4366-8354-e90816fbd408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KELUHAN PELANGGAN'])[1]/following::a[3]</value>
      <webElementGuid>0ec258cf-07ab-41db-8394-f71ba04609ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/preceding::a[2]</value>
      <webElementGuid>0e74c2f9-17ee-4aa1-b61e-4b4b9f2d2dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GANGGUAN PERLU PERHATIAN'])[1]/preceding::a[3]</value>
      <webElementGuid>8dac597c-2695-4ac1-830c-f3a5e4bb6c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='255']/parent::*</value>
      <webElementGuid>7f9a5d9e-6a14-4f7e-84f2-ab6288502357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/outage/monitoring/detail?type=kl&amp;data=y&amp;tab=1')]</value>
      <webElementGuid>10b6f100-6d46-4995-b911-aa79b42608db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/a[3]</value>
      <webElementGuid>3b0e0608-97ce-4886-9124-93ba51ee81b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/outage/monitoring/detail?type=kl&amp;data=y&amp;tab=1' and (text() = '255' or . = '255')]</value>
      <webElementGuid>be10d615-95a8-46bb-a9a8-49e3fab4987a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
