<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KLK_WO Keluhan Berulang</name>
   <tag></tag>
   <elementGuidId>b3c60670-414b-4518-a86c-8bcf12a3770e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[7]/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b546f715-ccc9-4611-bba2-3ee079e97586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-[#F31388] text-[14px] text-[#FFF] px-[8px] py-[4px] rounded-[50px]</value>
      <webElementGuid>1d09d93c-5887-4d54-8a1f-eb6e3680e814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Wo Keluhan Berulang PLN Mobile</value>
      <webElementGuid>a8c2bfe6-35a1-44a8-8c1d-29e0061b3a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/outage/monitoring/detail?type=trans&amp;data=kb&amp;tab=1</value>
      <webElementGuid>d7035457-0b77-437b-8568-f8664a0ed21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>74d79de1-fc11-4971-8ceb-095cf057bf5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;px-[64px] py-8 mx-auto mt-24 mb-28 max-w-screen-2xl relative&quot;]/div[@class=&quot;md:w-full lg:w-6/12 mx-auto mb-10&quot;]/div[@class=&quot;grid grid-cols-2 gap-4&quot;]/div[@class=&quot;rounded border-[1px] border-[#D9D9D9] p-4 justify-between h-full&quot;]/div[1]/a[@class=&quot;bg-[#F31388] text-[14px] text-[#FFF] px-[8px] py-[4px] rounded-[50px]&quot;]</value>
      <webElementGuid>41229ac7-4a60-4a22-b53d-f2f3cc44cfb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[7]/div/div[2]/div/a</value>
      <webElementGuid>d002865c-8645-4ee9-b3b7-6d5652f83bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'6')])[2]</value>
      <webElementGuid>a5dd3b91-3c1e-4db2-9b16-bb71ac11d23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KELUHAN PERHATIAN KHUSUS'])[1]/following::a[1]</value>
      <webElementGuid>3f921f39-b778-4f08-8e08-bf6b63521680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GANGGUAN PERLU PERHATIAN'])[1]/following::a[3]</value>
      <webElementGuid>546fa663-6a52-4fd4-a3a0-805c81bcb51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIPE KELUHAN'])[1]/preceding::a[1]</value>
      <webElementGuid>1c055101-89ac-42fd-93b7-75fad50d143d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pasang Baru'])[1]/preceding::a[1]</value>
      <webElementGuid>3d07f2cc-c495-4a8f-b35f-cb52d6b4758b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6']/parent::*</value>
      <webElementGuid>eeaec45b-7b9f-46cd-9c3b-62b8cf7f5f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/outage/monitoring/detail?type=trans&amp;data=kb&amp;tab=1')]</value>
      <webElementGuid>7d3f727b-233e-44c1-b977-18620b7c1233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/a</value>
      <webElementGuid>0f1ebf1f-c9b8-47b5-afd2-99adb28a927e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/outage/monitoring/detail?type=trans&amp;data=kb&amp;tab=1' and (text() = '6' or . = '6')]</value>
      <webElementGuid>45e9cfe7-d5cd-4747-8daf-09521d2c4780</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
