<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_EXPORT</name>
   <tag></tag>
   <elementGuidId>817abc2e-0aba-4434-a9cd-f4a03ac916c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-export</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-export']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3641f9f0-beff-4b0c-89f9-d914743b5121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-export</value>
      <webElementGuid>2a403275-285e-4c62-aa35-572cd5826b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vcc-btn  outlined-primary text-[12px] !px-[12px] !py-[9px] mr-2 !text-[#00A2B9] !border-[#82828233]</value>
      <webElementGuid>cfeaa122-ef27-48f4-b785-aef72f595637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EXPORT</value>
      <webElementGuid>1bfddefe-775d-465d-813a-c840b8e6cb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-export&quot;)</value>
      <webElementGuid>f0ec65a6-7d42-4c7d-9fa9-76976fedbef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-export']</value>
      <webElementGuid>31518839-19d2-4a0d-942b-2615371a6e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/button</value>
      <webElementGuid>ddd6dc9f-a1de-4de1-997f-a3fd99824b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian ID Pel Berdasarkan User'])[1]/following::button[1]</value>
      <webElementGuid>a8e23cba-25cd-435b-a20d-35bf15409d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/following::button[1]</value>
      <webElementGuid>0f774fac-8a2b-4a9a-b3d8-b695ebc185c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian'])[1]/preceding::button[1]</value>
      <webElementGuid>ad17de78-d593-4af0-a08b-52bc4244ab85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian ID Pel Berdasarkan User'])[2]/preceding::button[1]</value>
      <webElementGuid>847bdc7a-8953-4dc4-87bd-52299c67cdb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EXPORT']/parent::*</value>
      <webElementGuid>9148f41e-fbec-4c90-8530-b7c0d83995c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>21f8cdda-c657-49fe-8b88-219db77ee269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-export' and (text() = 'EXPORT' or . = 'EXPORT')]</value>
      <webElementGuid>25e7eade-f704-477b-a7a2-194f4200eb03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
