<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_EXPORT</name>
   <tag></tag>
   <elementGuidId>dc6504e7-5054-468e-a2fe-7009e0aad0bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f41bf1cf-1b62-4f61-979f-041b7cd40a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vcc-btn  outlined-primary text-[12px] !px-[12px] !py-[9px] mr-2 !text-[#00A2B9] !border-[#82828233]</value>
      <webElementGuid>8579ea22-442a-470f-8a30-5cd94707136f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EXPORT</value>
      <webElementGuid>530f0248-4e90-4505-bf34-7000e5ed3951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;px-[64px] py-8 mx-auto mt-28 mb-28 max-w-screen-2xl relative&quot;]/div[@class=&quot;flex items-center justify-between mt-49 mb-4 MuiBox-root css-0&quot;]/button[@class=&quot;vcc-btn  outlined-primary text-[12px] !px-[12px] !py-[9px] mr-2 !text-[#00A2B9] !border-[#82828233]&quot;]</value>
      <webElementGuid>713dcd13-97a2-4c16-80e2-47f0a806dfd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/button</value>
      <webElementGuid>818355c4-c196-4b86-9ea0-e512f933a527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/following::button[1]</value>
      <webElementGuid>5a4cfe9e-a260-420e-b6c5-52e9c17ce91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekap PLN Mobile'])[1]/preceding::button[1]</value>
      <webElementGuid>35acaddb-458c-4a17-8851-97a60019a104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekap Swacam'])[2]/preceding::button[1]</value>
      <webElementGuid>bf64a095-f6b9-4a7b-ba53-201bf09ba9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EXPORT']/parent::*</value>
      <webElementGuid>e5f32d9c-9a1b-422b-9e57-1033fac6b34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>086c1ce9-8e6a-4f5d-b19c-060b4bf79954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'EXPORT' or . = 'EXPORT')]</value>
      <webElementGuid>3287c80d-6235-4f5f-a048-67141c2543fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
