<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User_54614120-de9c-4210-a541-4b53c0c8f791</name>
   <tag></tag>
   <elementGuidId>3ac5a3ad-ad1d-4326-b3f7-cbfc100159bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;54614120-de9c-4210-a541-4b53c0c8f791&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='54614120-de9c-4210-a541-4b53c0c8f791']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>484489f0-f1f1-4e05-8881-21ae98b80307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input css-1m9pwf3</value>
      <webElementGuid>6a7256b5-42f3-4cdf-9143-d64c2492fbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>54614120-de9c-4210-a541-4b53c0c8f791</value>
      <webElementGuid>bb8e134e-294f-4267-af87-493a0c6186eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c54b062c-936e-4d96-8a83-6a00c8b8e5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1ccc94f3-8a17-4a8f-82cb-290fce5864c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;px-[64px] py-8 mx-auto mt-28 mb-28 max-w-screen-2xl relative&quot;]/form[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiFormControl-root MuiFormControl-fullWidth mb-8 css-tzsjye&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;py-1 px-3 border-b border-x border-[#E0E0E0] MuiBox-root css-0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiAccordion-root MuiAccordion-rounded MuiAccordion-gutters css-4of1v1&quot;]/div[@class=&quot;MuiButtonBase-root MuiAccordionSummary-root MuiAccordionSummary-gutters  css-xfnbgk&quot;]/div[@class=&quot;MuiAccordionSummary-content MuiAccordionSummary-contentGutters css-l0jafl&quot;]/label[@class=&quot;MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd css-1nq71mm&quot;]/span[@class=&quot;MuiButtonBase-root MuiCheckbox-root MuiCheckbox-colorPrimary MuiCheckbox-sizeMedium PrivateSwitchBase-root MuiCheckbox-root MuiCheckbox-colorPrimary MuiCheckbox-sizeMedium MuiCheckbox-root MuiCheckbox-colorPrimary MuiCheckbox-sizeMedium css-zun73v&quot;]/input[@class=&quot;PrivateSwitchBase-input css-1m9pwf3&quot;]</value>
      <webElementGuid>b1ff5062-a145-4e0c-8199-b0297f886191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='54614120-de9c-4210-a541-4b53c0c8f791']</value>
      <webElementGuid>df3e94b2-32ef-4dab-907b-f462e5d7f685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/form/div[5]/div/div[2]/div/div/div/label/span/input</value>
      <webElementGuid>ff08e5d4-d8f1-4b90-b23f-a7ba4dc6c390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/label/span/input</value>
      <webElementGuid>44b7b12b-dac8-4d1e-8967-d8f41307a429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '54614120-de9c-4210-a541-4b53c0c8f791' and @type = 'checkbox']</value>
      <webElementGuid>dbcc049a-4deb-4a95-95b9-650c284b8dae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
